export const SET_WIZARD_STEP = "SET_WIZARD_STEP";
export const SET_ACCOUNT_NUMBER = "SET_ACCOUNT_NUMBER";
export const SET_SIGNUP_CONFIRMATION = "SET_SIGNUP_CONFIRMATION";
export const SET_LOADER_ONBOARDING = "SET_LOADER_ONBOARDING";
export const SET_ERROR_PAYMENTMETHOD = "SET_ERROR_PAYMENTMETHOD";
export const SET_SUCCESS_PAYMENTMETHOD = "SET_SUCCESS_PAYMENTMETHOD";
export const SET_USER_DATA = "SET_USER_DATA";
export const CAMPAIGN_COMPLETED = "CAMPAIGN_COMPLETED";
